import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createServer } from 'node:http';
import { chromium } from 'playwright';
import { application } from './application-safe-helpers.js';

test('My Style in Chromium: branching builder, portable export, defaults, scoped drafts and mobile', {
  timeout: 90000, skip: !process.env.NUDGETHIS_TEST_BROWSER && 'Set NUDGETHIS_TEST_BROWSER to run browser interaction checks'
}, async t => {
  const site = createServer((req, res) => { res.writeHead(200, {'Content-Type':'text/html'});res.end('<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Style fixture</title><body><main><h1>Project settings</h1><button id="target">Save settings</button></main></body></html>'); });
  await new Promise(resolve => site.listen(0,'127.0.0.1',resolve));t.after(async()=>{site.closeAllConnections();await new Promise(resolve=>site.close(resolve));});
  const origin=`http://127.0.0.1:${site.address().port}`;
  const app=await application({origins:[origin]});t.after(()=>app.close());
  const browser=await chromium.launch({executablePath:process.env.NUDGETHIS_TEST_BROWSER,headless:true,args:['--no-sandbox']});t.after(()=>browser.close());
  const context=await browser.newContext({viewport:{width:1440,height:1080},reducedMotion:'reduce'});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`${app.address}/#token=${app.token}`);
  await page.getByRole('button',{name:'My Style',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'My Style',exact:true});
  const save=async()=>{await dialog.getByRole('button',{name:'Save style',exact:true}).click();await dialog.getByText('Saved. Existing conversations keep their captured style version.',{exact:true}).waitFor();};
  await dialog.getByRole('button',{name:'Editorial Let type and reading set the pace.'}).click();
  await dialog.getByRole('heading',{name:'What should lead the reading?'}).waitFor();
  await dialog.getByRole('button',{name:'Precise and direct Monospace headings with compact groups.'}).click();
  assert.equal(await dialog.getByLabel('Heading font',{exact:true}).inputValue(),'ui-monospace, monospace');
  await dialog.getByLabel('Style name',{exact:true}).fill('My studio');
  await dialog.getByRole('tab',{name:'Rules',exact:true}).click();
  await dialog.getByRole('button',{name:'Add a rule',exact:true}).click();
  await dialog.getByLabel('Rule 1 value',{exact:true}).fill('18px');
  await save();
  let library=(await app.api('/api/my-style')).data;const first=library.profiles[0];
  assert.equal(first.branch,'technical');assert.equal(first.rules[0].value,'18px');
  assert.equal(await dialog.locator('.ms-example-button').evaluate(e=>getComputedStyle(e).borderRadius),'18px');
  await dialog.getByRole('button',{name:'Use for new changes',exact:true}).click();
  await dialog.getByRole('button',{name:'Stop using by default',exact:true}).waitFor();
  const download=page.waitForEvent('download');await dialog.getByRole('button',{name:'Export style',exact:true}).click();
  const exported=JSON.parse(await readFile(await (await download).path(),'utf8'));
  assert.equal(exported.profile.name,'My studio');assert.equal(exported.profile.id,undefined);assert.equal(exported.profile.rules[0].evidence,undefined);
  const importing=page.waitForResponse(r=>r.url().endsWith('/api/my-style')&&r.request().method()==='POST');
  await dialog.locator('[data-file]').setInputFiles({name:'style.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...exported,profile:{...exported.profile,name:'Portable style'}}))});
  const importedResponse=await importing;assert.equal(importedResponse.status(),200,await importedResponse.text());
  await page.waitForFunction(()=>document.querySelector('#ms-name').value==='Portable style');
  library=(await app.api('/api/my-style')).data;const imported=library.profiles.find(p=>p.name==='Portable style');assert(imported);assert.notEqual(imported.id,first.id);
  await dialog.getByLabel('Apply to',{exact:true}).selectOption('page');
  await dialog.getByLabel('Page path',{exact:true}).fill('//example.com');
  await dialog.getByRole('button',{name:'Apply my style',exact:true}).click();
  await dialog.getByText('Enter a page path such as /settings, without a query or fragment.',{exact:true}).waitFor();
  await dialog.getByLabel('Page path',{exact:true}).fill('/settings');
  await dialog.getByRole('button',{name:'Apply my style',exact:true}).click();
  const composer=page.getByRole('dialog',{name:'New change',exact:true});
  await composer.getByText('Context for this change · 1 selected',{exact:true}).waitFor();
  assert.match(await composer.getByLabel('What needs to change?',{exact:true}).inputValue(),/page at \/settings/);
  assert(await composer.getByRole('button',{name:'Start change',exact:true}).isDisabled());
  await composer.getByRole('button',{name:'Save draft',exact:true}).click();await composer.waitFor({state:'hidden'});
  const readTasks=async()=>Promise.all((await app.api('/api/tasks')).data.map(async task=>(await app.api('/api/tasks/'+task.id)).data));
  let tasks=await readTasks();assert.equal(tasks.length,1);assert.equal(tasks[0].status,'draft');assert.deepEqual(tasks[0].projectContext.items.map(i=>i.id),[`my-${imported.id}`],'Explicit style replaces another default style');
  await page.getByRole('dialog',{name:'Task conversation',exact:true}).getByRole('button',{name:'Close task',exact:true}).click();
  await page.getByRole('button',{name:'New change',exact:true}).click();
  await composer.getByText('Context for this change · 1 selected',{exact:true}).waitFor();
  await composer.getByLabel('What needs to change?',{exact:true}).fill('Keep the profile controls readable.');
  await composer.getByRole('button',{name:'Save draft',exact:true}).click();await composer.waitFor({state:'hidden'});
  tasks=await readTasks();assert(tasks.some(task=>task.request==='Keep the profile controls readable.'&&task.projectContext.items[0].id===`my-${first.id}`));
  await page.getByRole('dialog',{name:'Task conversation',exact:true}).getByRole('button',{name:'Close task',exact:true}).click();
  await page.getByRole('button',{name:'My Style',exact:true}).click();
  await dialog.getByRole('tab',{name:'Suggestions',exact:true}).click();
  await dialog.getByText(/No repeated corrections found yet/).waitFor();
  // A stale window must keep its unsaved choices when a newer revision exists.
  library=(await app.api('/api/my-style')).data;
  assert.equal((await app.api('/api/my-style',{method:'POST',body:JSON.stringify({action:'reset-dismissed',revision:library.revision})})).status,200);
  await dialog.getByLabel('Style name',{exact:true}).fill('Unsaved name');await dialog.getByRole('button',{name:'Save style',exact:true}).click();
  await dialog.getByText('My Style changed in another window. Reload before saving.',{exact:true}).waitFor();
  assert.equal(await dialog.getByLabel('Style name',{exact:true}).inputValue(),'Unsaved name');
  page.once('dialog',d=>d.accept());await dialog.getByRole('button',{name:'Reload saved',exact:true}).click();
  await dialog.getByText('Saved locally · v1',{exact:true}).waitFor();
  await dialog.getByRole('button',{name:'Close',exact:true}).click();

  const phoneContext=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const phone=await phoneContext.newPage();phone.on('pageerror',e=>errors.push(e.message));
  await phone.goto(origin+'/settings');await phone.evaluate(async({server,token})=>{const {NudgeThis}=await import(`${server}/overlay.js`);window.overlay=NudgeThis.init({enabled:true,server,token});},{server:app.address,token:app.token});
  await phone.getByRole('button',{name:'Pick element',exact:true}).tap();await phone.locator('#target').tap();
  await phone.locator('.panel').getByRole('button',{name:'My Style',exact:true}).tap();
  const mobile=phone.getByRole('dialog',{name:'My Style',exact:true});await mobile.getByText('Saved locally · v1',{exact:true}).waitFor();
  assert.equal(await mobile.getByLabel('Apply to',{exact:true}).inputValue(),'element');
  assert(await mobile.evaluate(e=>e.scrollWidth<=e.clientWidth),'No horizontal overflow on mobile');
  await mobile.getByRole('button',{name:'Apply my style',exact:true}).tap();
  const mobileComposer=phone.getByRole('dialog',{name:'New change',exact:true});await mobileComposer.getByText('Context for this change · 1 selected',{exact:true}).waitFor();
  await mobileComposer.getByRole('button',{name:'Save draft',exact:true}).tap();await mobileComposer.waitFor({state:'hidden'});
  tasks=await readTasks();const selected=tasks.find(task=>task.request.includes('selected element'));assert.equal(selected.context.tagName,'button');assert.equal(selected.context.route,'/settings');
  assert(tasks.every(task=>task.status==='draft'));assert.equal((await app.api('/api/status')).data.executionEnabled,false);assert.deepEqual(errors,[]);
});
