import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { application } from './application-safe-helpers.js';
const options = { timeout: 90000, skip: !process.env.NUDGETHIS_TEST_BROWSER && 'Set NUDGETHIS_TEST_BROWSER for browser checks' };
test('Welcome creates a website, opens its real preview and retains context on desktop and mobile', options, async t => {
  const app = await application({ repository: 'none' }); t.after(() => app.close());
  const browser = await chromium.launch({ executablePath: process.env.NUDGETHIS_TEST_BROWSER, headless: true, args: ['--no-sandbox'] }); t.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } }), errors = [];
  page.on('pageerror', e => errors.push(e.message)); await page.goto(`${app.address}/welcome#token=${app.token}`);
  await page.getByRole('button', { name: /Start from an idea/ }).click();
  await page.getByLabel('Who is it for?').fill('People in my neighborhood');
  await page.getByLabel('What should people be able to do?').fill('See the menu and find our bakery');
  await page.getByRole('button', { name: 'Find my starting point →' }).click();
  await page.getByLabel('Project folder name').fill('neighborhood-bakery');
  await page.getByRole('button', { name: 'Review project setup →' }).click();
  await page.getByRole('heading', { name: 'Your first version starts here.' }).waitFor();
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  const open = page.getByRole('link', { name: 'Open workspace & preview →' }); await open.waitFor();
  const [workspace] = await Promise.all([page.waitForEvent('popup'), open.click()]); workspace.on('pageerror', e => errors.push(e.message));
  const preview = workspace.getByRole('dialog', { name: 'Project preview', exact: true });
  await preview.getByRole('button', { name: 'Review preview startup' }).click();
  await preview.getByRole('button', { name: 'Start preview', exact: true }).click();
  const link = preview.getByRole('link', { name: 'Open preview ↗' }); await link.waitFor();
  const [site] = await Promise.all([workspace.waitForEvent('popup'), link.click()]); site.on('pageerror', e => errors.push(e.message));
  await site.getByText('See the menu and find our bakery', { exact: true }).waitFor();
  await site.locator('[data-nudgethis-overlay] .launcher').waitFor();
  assert.equal(new URL(site.url()).hash, '', 'Preview token is removed from the address');
  await preview.getByRole('button', { name: 'Stop preview', exact: true }).click();
  await preview.getByText('Your preview is stopped. Files are kept.', { exact: true }).waitFor();
  await preview.getByRole('button', { name: 'Close', exact: true }).click();
  await workspace.locator('#context-button').click();
  await workspace.getByRole('dialog', { name: 'Project context', exact: true }).getByRole('button', { name: /^Project goal and starting decisions/ }).waitFor();
  const phone = await browser.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true }); phone.on('pageerror', e => errors.push(e.message));
  await phone.goto(`${app.address}/welcome#token=${app.token}`);
  await phone.getByRole('button', { name: /Use a starter/ }).tap();
  await phone.getByRole('button', { name: 'Choose Interactive app', exact: true }).tap();
  await phone.getByLabel('Who is it for?').fill('Me'); await phone.getByLabel('What should people be able to do?').fill('Keep a list of ideas'); await phone.getByLabel('What are you building?').selectOption('app');
  await phone.getByRole('button', { name: 'Find my starting point →' }).tap();
  assert(await phone.locator('input[name=template][value=react]').isChecked());
  assert(await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Welcome fits a phone');
  if (process.env.NUDGETHIS_TEST_SCREENSHOT) await phone.screenshot({ path: process.env.NUDGETHIS_TEST_SCREENSHOT, fullPage: true });
  assert.deepEqual(errors, []);
});
