export const paletteStyles = `
.palette-launcher,.palette-target{display:inline-flex;align-items:center;justify-content:center;gap:7px;pointer-events:auto;padding:12px;border:1px solid var(--dr-border);border-radius:var(--dr-radius);background:var(--dr-surface);color:var(--dr-text)}
.palette-launcher[aria-expanded=true]{background:var(--dr-accent);color:var(--dr-onAccent);border-color:var(--dr-accent)}
.palette-target{padding:7px 10px;margin:0 0 12px;font-size:calc(var(--dr-size) * .86)}
.overlay-tools[data-side=left]{left:20px;right:auto;justify-content:flex-start}
.overlay-tools .tp-dock-control{display:inline-flex;align-items:center;justify-content:center;gap:6px;min-width:44px;min-height:44px}
.overlay-tools .launcher{max-width:100%;min-width:0}.overlay-tools .launcher .label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.tool-palette{position:fixed;right:20px;bottom:88px;width:min(328px,calc(100vw - 24px));max-height:calc(100dvh - 108px);display:flex;flex-direction:column;pointer-events:auto;z-index:7;border:1px solid var(--dr-border);border-radius:var(--dr-radius);background:var(--dr-surface);color:var(--dr-text);box-shadow:0 8px 32px color-mix(in srgb,var(--dr-backdrop) 18%,transparent);font:var(--dr-size)/1.5 var(--dr-font-body);text-align:left}
.tool-palette[data-side=left]{left:20px;right:auto}
.tool-palette button,.tool-palette select,.tool-palette input,.tool-palette textarea{font:inherit;color:var(--dr-text);border:1px solid var(--dr-border);border-radius:var(--dr-radius);background:var(--dr-surface)}
.tool-palette button:disabled{cursor:not-allowed}.tool-palette button:hover:not(:disabled){border-color:var(--dr-accent)}
.tp-header{padding:16px;display:flex;align-items:center;justify-content:space-between;gap:8px}.tp-header small{font-size:10px;letter-spacing:.1em;color:var(--dr-accent);font-weight:700}.tp-header h2{font:700 calc(var(--dr-size) * 1.2)/1.35 var(--dr-font-heading);margin:4px 0 0}.tp-collapse{display:grid;place-items:center;padding:7px;min-width:36px;min-height:36px}
.tp-tabs{display:flex;padding:0 16px;border-bottom:1px solid var(--dr-border);gap:16px}.tp-tabs button{padding:10px 4px;border:0;border-bottom:2px solid transparent;border-radius:0;flex:1}.tp-tabs button[aria-selected=true]{border-bottom-color:var(--dr-accent);font-weight:700;color:var(--dr-accent)}
.tp-content{overflow:auto;overscroll-behavior:contain;min-height:0;padding:14px 16px}.tp-help{font-size:calc(var(--dr-size) * .86);color:var(--dr-muted);margin:8px 0 14px;line-height:1.6}.tp-selection{font-size:calc(var(--dr-size) * .86);margin:0 0 10px;color:var(--dr-accent);font-weight:700}.tp-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}
.tp-card{position:relative;min-width:0}.tp-choice{display:flex;flex-direction:column;align-items:flex-start;text-align:left;width:100%;height:100%;padding:12px 10px;gap:7px}.tp-choice[aria-pressed=true]{background:var(--dr-accentSoft);border-color:var(--dr-accent)}.tp-choice strong{font-size:calc(var(--dr-size) * .86)}.tp-choice small{font-size:calc(var(--dr-size) * .75);line-height:1.5;color:var(--dr-muted)}
.tool-palette .tp-favorite{position:absolute;right:2px;top:2px;width:30px;height:30px;padding:6px;display:grid;place-items:center;border-color:transparent;background:var(--dr-surface)}.tp-favorite .nt-icon{width:16px;height:16px}.tp-favorite[aria-pressed=true]{color:var(--dr-accent)}.tp-favorite[aria-pressed=true] .nt-icon{fill:var(--dr-accentSoft)}
.tp-sample{display:flex;align-items:center;justify-content:flex-start;min-height:30px;width:100%;color:var(--dr-accent);padding-right:18px}.tp-element-grid .tp-sample{height:74px;justify-content:center;padding:8px 0;color:var(--dr-text)}.tp-sample-button{font-size:10px;padding:7px 9px;color:var(--dr-onAccent);background:var(--dr-accent);border-radius:var(--dr-radius)}.tp-sample-text,.tp-sample-card,.tp-sample-input,.tp-sample-section{display:flex;flex-direction:column;width:100%;gap:5px}.tp-sample b{font-size:11px}.tp-sample i{display:block;height:4px;background:var(--dr-border);border-radius:2px;width:85%}.tp-sample-text i:last-child{width:60%}.tp-sample-image{display:grid;place-items:center;width:100%;height:55px;border:1px dashed var(--dr-accent);background:var(--dr-accentSoft)}.tp-sample-card{padding:7px;border:1px solid var(--dr-border);background:var(--dr-surface)}.tp-sample-card i{background:var(--dr-accentSoft);height:12px;width:100%}.tp-sample-card small,.tp-sample-input small{font-size:8px}.tp-sample-input i{border:1px solid var(--dr-border);font-style:normal;font-size:8px;height:auto;padding:7px;width:100%;background:var(--dr-surface);color:var(--dr-muted)}.tp-sample-section{background:var(--dr-accentSoft);padding:12px 7px}.tp-sample-section i{width:100%}
.tp-inspector{border-top:1px solid var(--dr-border);margin-top:16px;padding-top:12px}.tp-inspector h3{font:700 var(--dr-size)/1.5 var(--dr-font-heading);margin:0 0 10px}.tp-fields label{display:block;font-size:calc(var(--dr-size) * .86);color:var(--dr-muted);margin:10px 0}.tp-fields input,.tp-fields select,.tp-fields textarea{display:block;width:100%;padding:8px;margin-top:5px}.tp-fields textarea{height:76px;resize:vertical}.tp-fields input[type=color]{height:42px;padding:4px}.tp-inspector .tp-prepare{width:100%;padding:10px;background:var(--dr-accent);color:var(--dr-onAccent);border-color:var(--dr-accent);font-weight:700}.tp-pick{width:100%;padding:9px;margin-bottom:8px}.tp-error{font-size:12px;color:var(--dr-danger);overflow-wrap:anywhere;margin:8px 0}.tp-error:empty,.tp-requirement:empty{display:none}
.tp-shortcuts{display:flex;gap:8px;margin-top:16px}.tp-shortcuts button{display:flex;align-items:center;justify-content:center;gap:5px;flex:1;padding:9px 5px;font-size:calc(var(--dr-size) * .8)}.tp-shortcuts .nt-icon{width:16px;height:16px}
.tp-footer{border-top:1px solid var(--dr-border);padding:10px 16px}.tp-footer label{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:0}.tp-footer select{padding:4px 8px}.tp-footer small,.tp-storage{font-size:10px;color:var(--dr-muted)}.tp-storage{margin:4px 0}
@media(max-width:900px){.overlay-tools .tp-dock-control>span{position:absolute;clip-path:inset(50%);width:1px;height:1px;overflow:hidden;white-space:nowrap}}
@media(max-width:700px){.tool-palette{bottom:140px;max-height:calc(100dvh - 152px)}.overlay-tools[data-side=left]{left:12px}.tool-palette,.tool-palette[data-side=left]{right:12px;left:auto}.tp-header{padding:10px 14px}.tp-content{padding:10px 14px}.tp-footer{padding:8px 14px}}
@media(prefers-reduced-motion:no-preference){.tp-choice,.palette-launcher{transition:background-color .12s,border-color .12s}}
`;
